# ---
spring:
  profiles:
    active: pg
  batch:
    job:
      enabled: false
  quartz:
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
# ---
# spring:
# #   config.activate.on-profile: default
#   # sql.init.schema-locations: classpath:schema-h2.sql
#   config:
#     activate:
#       on-profile:
#       - dev
  # datasource:
  #   url: "jdbc:sqlite:db.sqlite"
  #   driver-class-name: org.sqlite.JDBC
  #   hikari:
  #     maximum-pool-size: 10
---
spring:
  web.resources.static-locations: "file:./app"
  config:
    activate:
      on-profile: pg
  datasource:
    url: jdbc:postgresql://localhost:5432/batchimportcat
    username: haihuazhang
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  sql:
    init:
      mode: always
      schema-locations:
        # - classpath:schema-pg-reset.sql
        # - classpath:org/springframework/batch/core/schema-drop-postgresql.sql
        # - classpath:org/springframework/batch/core/schema-postgresql.sql
        # - classpath:org/quartz/impl/jdbcjobstore/tables_postgres.sql
        # - classpath:schema-pg-compat.sql
        - classpath:schema.sql
  batch:
    jdbc:
      initialize-schema: NEVER
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: NEVER
cds:
  dataSource:
    auto-config.enabled: true

---
spring:
  web.resources.static-locations: "file:./app/,file:../app/,file:./dataimportplatformcap/app/"
  config:
    activate:
      on-profile: hybrid
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: NEVER
cds:
  dataSource:
    auto-config.enabled: true


# ---
# spring:
#   config:
#     activate:
#       on-profile:
#       - prod
# cds:
#   dataSource:
#     auto-config.enabled: true
#     xxx-db:
#       maximum-pool-size: 100
