# ---
spring:
  profiles:
    default: pg
  batch:
    job:
      enabled: false
# ---
# spring:
# #   config.activate.on-profile: default
#   # sql.init.schema-locations: classpath:schema-h2.sql
#   config:
#     activate:
#       on-profile:
#       - dev
  # datasource:
  #   url: "jdbc:sqlite:db.sqlite"
  #   driver-class-name: org.sqlite.JDBC
  #   hikari:
  #     maximum-pool-size: 10
---
spring:
  web.resources.static-locations: "file:./app"
  config:
    activate:
      on-profile: pg
  datasource:
    url: jdbc:postgresql://localhost:5432/batchimportcat
    username: haihuazhang
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  sql:
    init:
      mode: always
      schema-locations:
        # - classpath:schema-pg-reset.sql
        # - classpath:org/springframework/batch/core/schema-drop-postgresql.sql
        # - classpath:org/springframework/batch/core/schema-postgresql.sql
        # - classpath:org/quartz/impl/jdbcjobstore/tables_postgres.sql
        # - classpath:schema-pg-compat.sql
        - classpath:schema.sql
  batch:
    jdbc:
      initialize-schema: NEVER
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: NEVER
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
cds:
  dataSource:
    auto-config.enabled: true
batchimport:
  task:
    launcher-type: cloudfoundry
    host-app: batchimportcat-batch-task
    memory-mb: 1024
    disk-mb: 1024
    timeout: 1h
    cloudfoundry:
      api-host: api.cf.us10-001.hana.ondemand.com
      organization: a83421e9trial
      space: dev
      username: ${BATCHIMPORT_TASK_CLOUDFOUNDRY_USERNAME:}
      password: ${BATCHIMPORT_TASK_CLOUDFOUNDRY_PASSWORD:}
      skip-ssl-validation: false
      command-template: "{defaultCommand} --fileUUID={fileUUID} --executionUUID={executionUUID}"

---
spring:
  web.resources.static-locations: "file:./app/,file:../app/,file:./dataimportplatformcap/app/"
  config:
    activate:
      on-profile: hybrid
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: NEVER
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
cds:
  dataSource:
    auto-config.enabled: true
batchimport:
  task:
    launcher-type: local
    host-app: batchimportcat-batch-task
    memory-mb: 1024
    disk-mb: 1024
    timeout: 1h
    local:
      shell: /bin/zsh
      batch-task-jar: batch-task/target/batchimportcat-batch-task-exec.jar

---
spring:
  config:
    activate:
      on-profile: cloud
  batch:
    jdbc:
      initialize-schema: NEVER
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: NEVER
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
cds:
  dataSource:
    auto-config.enabled: true
batchimport:
  task:
    launcher-type: "${BATCHIMPORT_TASK_LAUNCHER_TYPE:cloudfoundry}"
    host-app: "${BATCHIMPORT_TASK_HOST_APP:batchimportcat-batch-task}"
    memory-mb: 1024
    disk-mb: 1024
    timeout: 1h
    cloudfoundry:
      api-host: ${BATCHIMPORT_TASK_CLOUDFOUNDRY_API_HOST:}
      organization: ${BATCHIMPORT_TASK_CLOUDFOUNDRY_ORGANIZATION:}
      space: ${BATCHIMPORT_TASK_CLOUDFOUNDRY_SPACE:}
      username: ${BATCHIMPORT_TASK_CLOUDFOUNDRY_USERNAME:}
      password: ${BATCHIMPORT_TASK_CLOUDFOUNDRY_PASSWORD:}
      skip-ssl-validation: false
      command-template: "${BATCHIMPORT_TASK_CLOUDFOUNDRY_COMMAND_TEMPLATE:{defaultCommand} --fileUUID={fileUUID} --executionUUID={executionUUID}}"


# ---
# spring:
#   config:
#     activate:
#       on-profile:
#       - prod
# cds:
#   dataSource:
#     auto-config.enabled: true
#     xxx-db:
#       maximum-pool-size: 100
